name: Auto update generated library
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
env:
  library_last_version: 0.0.0
  template_last_version: 0.0.0
  template_current_version: 0.0.0
  document_last_version: 0.0.0
  document_current_version: 0.0.0
  major_template_last_version: 0
  minor_template_last_version: 0
  patch_template_last_version: 0
  major_template_current_version: 0
  minor_template_current_version: 0
  patch_template_current_version: 0
  major_version_change: false
  minor_version_change: false
  patch_version_change: false
  commit_message: ""
jobs:
  get-template-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get utility library
        uses: actions/checkout@v2  
        with:
          repository: tyleradams/json-toolkit
          path: "./tooling"
      - name: Install and build utility tools
        run: cd ./tooling && make && sudo make install && cd ..
      - uses: actions/checkout@v2
      # Find all relevant semver versions needed to figure out how to update the client
      - name: Fetch the last AsyncAPI document version that generated the client
        run: echo "document_last_version=$(cat ./configs.json | jq -r '.document_last_version')" >> $GITHUB_ENV
      - name: Fetch the last template version that generated the client
        run: echo "template_last_version=$(cat ./configs.json | jq -r '.template_last_version')" >> $GITHUB_ENV
      - name: Fetch the last library version
        run: echo "library_last_version=$(cat ./AsyncapiNatsClient/AsyncapiNatsClient.csproj | xml-to-json | jq -r '.Project.PropertyGroup.Version')" >> $GITHUB_ENV
      - name: Fetch current template version
        run: echo "template_current_version=$(curl -sL https://api.github.com/repos/asyncapi/dotnet-nats-template/releases/latest | jq -r '.tag_name' | sed 's/v//')" >> $GITHUB_ENV
      - name: Get all the application AsyncAPI documents
        uses: actions/checkout@v2  
        with:
          repository: GamingAPI/definitions
          path: "./definitions"
      - name: Get the version of the API
        run: echo "document_current_version=$(cat ./definitions/<<[ .cus.ASYNCAPI_FILE ]>> | jq -r '.info.version' | sed 's/v//')" >> $GITHUB_ENV
      
      # Figure out how the template version have changed
      - run: semver_template_last_version=( ${template_last_version//./ } ) && major_template_last_version=${semver_template_last_version[0]} && echo "major_template_last_version=$major_template_last_version" >> $GITHUB_ENV
      - run: semver_template_last_version=( ${template_last_version//./ } ) && minor_template_last_version=${semver_template_last_version[1]} && echo "minor_template_last_version=$minor_template_last_version" >> $GITHUB_ENV
      - run: semver_template_last_version=( ${template_last_version//./ } ) && patch_template_last_version=${semver_template_last_version[2]} && echo "patch_template_last_version=$patch_template_last_version" >> $GITHUB_ENV
      - run: semver_template_current_version=( ${template_current_version//./ } ) && major_template_current_version=${semver_template_current_version[0]} && echo "major_template_current_version=$major_template_current_version" >> $GITHUB_ENV
      - run: semver_template_current_version=( ${template_current_version//./ } ) && minor_template_current_version=${semver_template_current_version[1]} && echo "minor_template_current_version=$minor_template_current_version" >> $GITHUB_ENV
      - run: semver_template_current_version=( ${template_current_version//./ } ) && patch_template_current_version=${semver_template_current_version[2]} && echo "patch_template_current_version=$patch_template_current_version" >> $GITHUB_ENV
      - if: ${{ env.major_template_current_version > env.major_template_last_version }}
        run: echo "major_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}Template have changed to a new major version." >> $GITHUB_ENV
      - if: ${{ env.minor_template_current_version > env.minor_template_last_version }}
        run: echo "minor_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}Template have changed to a new minor version." >> $GITHUB_ENV
      - if: ${{ env.patch_template_current_version > env.patch_template_last_version }}
        run: echo "patch_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}Template have changed to a new patch version." >> $GITHUB_ENV

      # Figure out how the AsyncAPI document have changed
      - run: semver_document_last_version=( ${document_last_version//./ } ) && major_document_last_version=${semver_document_last_version[0]} && echo "major_document_last_version=$major_document_last_version" >> $GITHUB_ENV
      - run: semver_document_last_version=( ${document_last_version//./ } ) && minor_document_last_version=${semver_document_last_version[1]} && echo "minor_document_last_version=$minor_document_last_version" >> $GITHUB_ENV
      - run: semver_document_last_version=( ${document_last_version//./ } ) && patch_document_last_version=${semver_document_last_version[2]} && echo "patch_document_last_version=$patch_document_last_version" >> $GITHUB_ENV
      - run: semver_document_current_version=( ${document_current_version//./ } ) && major_document_current_version=${semver_document_current_version[0]} && echo "major_document_current_version=$major_document_current_version" >> $GITHUB_ENV
      - run: semver_document_current_version=( ${document_current_version//./ } ) && minor_document_current_version=${semver_document_current_version[1]} && echo "minor_document_current_version=$minor_document_current_version" >> $GITHUB_ENV
      - run: semver_document_current_version=( ${document_current_version//./ } ) && patch_document_current_version=${semver_document_current_version[2]} && echo "patch_document_current_version=$patch_document_current_version" >> $GITHUB_ENV
      - if: ${{ env.major_document_current_version > env.major_document_last_version }}
        run: echo "major_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}AsyncAPI document have changed to a new major version. " >> $GITHUB_ENV
      - if: ${{ env.minor_document_current_version > env.minor_document_last_version && env.major_document_current_version < env.major_document_last_version }}
        run: echo "minor_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}AsyncAPI document have changed to a new minor version. " >> $GITHUB_ENV
      - if: ${{ env.patch_document_current_version > env.patch_document_last_version && env.minor_document_current_version < env.minor_document_last_version && env.major_document_current_version < env.major_document_last_version }}
        run: echo "patch_version_change=true" >> $GITHUB_ENV && echo "commit_message=${commit_message}AsyncAPI document have changed to a new patch template version. " >> $GITHUB_ENV

      # Make changes to the code if needed
      - name: Remove previous files to ensure clean slate
        if: ${{env.major_version_change == 'true' || env.minor_version_change == 'true' || env.patch_version_change == 'true'}}
        run: find . -not \( -name configs.json -or -name .gitignore -or -iwholename *.github* -or -iwholename *./definitions* -or -iwholename *.git* -or -name . \) -exec echo {} +
      - name: Generating code from the AsyncAPI document
        if: ${{env.major_version_change == 'true' || env.minor_version_change == 'true' || env.patch_version_change == 'true'}}
        uses: docker://asyncapi/github-action-for-generator:2.0.0
        with:
          template: '@asyncapi/ts-nats-template'
          filepath: ./definitions/<<[ .cus.ASYNCAPI_FILE ]>>
          output: ./
          parameters: "version=${{env.library_last_version}}"
      - name: Write new config file to ensure we keep the new state for next time
        if: ${{env.major_version_change == 'true' || env.minor_version_change == 'true' || env.patch_version_change == 'true'}}
        run: |
          contents="$(jq ".template_last_version = \"$template_current_version\" | .document_last_version = \"$document_current_version\"" configs.json)" && echo "${contents}" > configs.json
      
      # Clean up from code generation
      - name: Remove excess files
        if: ${{env.major_version_change == 'true' || env.minor_version_change == 'true' || env.patch_version_change == 'true'}}
        run: rm -rf ./definitions && rm -rf ./tooling

      # Follow conventional commit for PR's to ensure accurate updates
      - name: Create pull request for major version if needed
        if: ${{env.major_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat!: major version change"
          committer: GamingEventapiBot <gamingeventapi@gmail.com>
          author: GamingEventapiBot <gamingeventapi@gmail.com>
          delete-branch: true
          commit-message: ${{env.commit_message}}. Library require a new major version change.
          body: ${{env.commit_message}}. Library require a new major version change.
      - name: Create pull request for minor version if needed
        if: ${{env.major_version_change == 'false' && env.minor_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v3
        with:
          title: "feat: minor version change"
          committer: GamingEventapiBot <gamingeventapi@gmail.com>
          author: GamingEventapiBot <gamingeventapi@gmail.com>
          delete-branch: true
          commit-message: ${{env.commit_message}}. Library require a new minor version change.
          body: ${{env.commit_message}}. Library require a new minor version change.
      - name: Create pull request for patch version if needed
        if: ${{env.major_version_change == 'false' && env.minor_version_change == 'false' && env.patch_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v3
        with:
          title: "fix: patch version change"
          committer: GamingEventapiBot <gamingeventapi@gmail.com>
          author: GamingEventapiBot <gamingeventapi@gmail.com>
          delete-branch: true
          commit-message: ${{env.commit_message}}. Library require a new patch version change.
          body: ${{env.commit_message}}. Library require a new patch version change.